openapi: 3.0.0
info:
  title: myIoT
  version: '1.0'
  description: ''
  contact: {}
  license:
    name: MasterIT technologies a.s.
servers:
  - url: 'https://develop.masterit.cz'
    description: develop
paths:
  /api/customer/email/exist:
    get:
      summary: CheckLogin
      operationId: get-api-customer-email-exist
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIResult'
              examples:
                OK - email existuje:
                  value:
                    status: ok
                    err_msg: ''
                    err_code: 0
                    data: true
                OK - email neexistuje:
                  value:
                    status: ok
                    err_msg: ''
                    err_code: 0
                    data: false
      description: Metoda zkontroluje existenci emailu pro danou aplikaci
      tags:
        - authorization
      parameters:
        - schema:
            type: string
          in: query
          name: email
          description: email u kterého zjišťujeme existenci
          required: true
        - schema:
            type: string
            example: myIoT
          in: query
          name: app
          description: 'aplikace pro kterou, zjištujeme existenci emailu'
          required: true
    parameters: []
components:
  schemas:
    APIResult:
      title: APIResult
      type: object
      properties:
        status:
          type: string
        err_msg:
          type: string
        err_code:
          type: integer
        data:
          type:
            - 'null'
            - object
      x-examples:
        OK:
          status: ok
          err_msg: ''
          err_code: 0
          data: null
        ERROR:
          status: error
          err_msg: Nedostatečné oprávnění
          err_code: -4000
          data: null
  securitySchemes:
    Bearer token:
      type: http
      scheme: bearer
